trigger:
  branches:
    include:
      - main

variables:
  - group: terraform-envs  # includes AWS_REGION, TF_VAR_ami_id, TF_VAR_instance_type

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform
  jobs:
  - job: Plan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformCLI@1
      displayName: 'Init Terraform'
      inputs:
        command: init
        workingDirectory: terraform

    - task: TerraformCLI@1
      displayName: 'Plan Terraform'
      inputs:
        command: plan
        workingDirectory: terraform
        environmentServiceNameAws: 'AWS_CONNECTION'
      env:
        AWS_REGION: $(AWS_REGION)
        TF_VAR_ami_id: $(TF_VAR_ami_id)
        TF_VAR_instance_type: $(TF_VAR_instance_type)

  - job: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    steps:
    - task: TerraformCLI@1
      displayName: 'Apply Terraform'
      inputs:
        command: apply
        workingDirectory: terraform
        args: '-auto-approve'
        environmentServiceNameAws: 'AWS_CONNECTION'
      env:
        AWS_REGION: $(AWS_REGION)
        TF_VAR_ami_id: $(TF_VAR_ami_id)
        TF_VAR_instance_type: $(TF_VAR_instance_type)
