trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: aws-manasa

steps:
- task: UsePythonVersion@0
  displayName: 'Install AWS CLI'
  inputs:
    versionSpec: '3.x'
- script: |
    python3 -m pip install awscli --upgrade --user
    echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc
    source ~/.bashrc
    aws --version
  displayName: 'Install AWS CLI via pip'

- task: DownloadSecureFile@1
  displayName: 'Download PEM file'
  inputs:
    secureFile: 'mykeypair.pem'
    targetPath: '$(Agent.TempDirectory)'

- task: CopyFiles@2
  displayName: 'Prepare index.html'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'index.html'
    TargetFolder: '$(Agent.TempDirectory)'

- script: |
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    aws configure set region $(AWS_REGION)
  displayName: 'Configure AWS Credentials'

- script: |
    set -e
    instance_id=$(aws ec2 run-instances \
      --image-id ami-0b990d3cfca306617 \
      --instance-type t2.micro \
      --key-name mykeypair \
      --subnet-id subnet-01d2eeadfc5a59d62 \
      --security-group-ids sg-05cb59f6315e06990 \
      --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=by-az-using-PEM}]' \
      --query 'Instances[0].InstanceId' \
      --output text)
    echo "Launched instance: $instance_id"

    aws ec2 wait instance-running --instance-ids "$instance_id"
    public_ip=$(aws ec2 describe-instances \
      --instance-ids "$instance_id" \
      --query 'Reservations[0].Instances[0].PublicIpAddress' \
      --output text)
    echo "Public IP: $public_ip"

    chmod 600 "$(Agent.TempDirectory)/mykeypair.pem"
    ssh_opts="-o StrictHostKeyChecking=no -i $(Agent.TempDirectory)/mykeypair.pem ec2-user@$public_ip"

    ssh $ssh_opts << 'EOH'
      sudo yum update -y
      sudo yum install -y httpd
      sudo systemctl start httpd
      sudo systemctl enable httpd
      sudo chmod 777 /var/www/html/
      sudo chown ec2-user:ec2-user /var/www/html/
    EOH

    scp -o StrictHostKeyChecking=no \
      -i "$(Agent.TempDirectory)/mykeypair.pem" \
      "$(Agent.TempDirectory)/index.html" \
      ec2-user@$public_ip:/var/www/html/index.html

    echo "Deployment complete: http://$public_ip/"
  displayName: 'Launch EC2 & Deploy index.html'
